---
# tasks/main.yml

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure MSMTP related packages are installed
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ msmtp_packages }}"

- name: Ensure msmtp conf dir presents
  file:
    path: "/etc/msmtp"
    state: "directory"
    mode: "{{ msmtp_rcdir_mode }}"
    owner: "{{ msmtp_rcfile_owner }}"
    group: "{{ msmtp_rcfile_group }}"

- name: Ensure account specific msmtprc conf files are present
  template:
    src: "msmtprc.j2"
    dest: "/etc/msmtp/msmtprc{{ (item.name == 'default') | ternary('.000.', '.') }}{{ item.name }}"
    mode: "{{ msmtp_rcfile_mode }}"
    owner: "{{ msmtp_rcfile_owner }}"
    group: "{{ msmtp_rcfile_group }}"
  with_items:
    - "{{ msmtp_accounts }}"

- name: Ensure account specific aliases conf files are present
  template:
    src: "aliases.j2"
    dest: "/etc/msmtp/aliases{{ (item.name == 'default') | ternary('.000.', '.') }}{{ item.name }}"
    mode: "{{ msmtp_rcfile_mode }}"
    owner: "{{ msmtp_rcfile_owner }}"
    group: "{{ msmtp_rcfile_group }}"
  with_items:
    - "{{ msmtp_accounts }}"

- name: Ensure account specific log files are exist and have valid permissions
  file:
    state: "touch"
    dest: "{{ item.logfile }}"
    mode: "{{ msmtp_logfile_mode }}"
    owner: "{{ msmtp_logfile_owner }}"
    group: "{{ msmtp_logfile_group }}"
  when: item.log == 'file' and item.logfile is defined
  with_items:
    - "{{ msmtp_accounts }}"

- name: Assemble msmtp config file from fragmets
  assemble:
    src: /etc/msmtp
    dest: /etc/msmtprc
    mode: "{{ msmtp_rcfile_mode }}"
    owner: "{{ msmtp_rcfile_owner }}"
    group: "{{ msmtp_rcfile_group }}"
    delimiter: ""
    regexp: "^msmtprc\\..+"
