---
# tasks/main.yml

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure MSMTP related packages are installed
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ msmtp_packages }}"

- name: Ensure msmtp conf dir presents
  file:
    path: "/etc/msmtp"
    state: "directory"
    mode: "0750"
    owner: "{{ msmtp_owner }}"
    group: "{{ msmtp_group }}"

- name: Ensure account specific msmtprc conf files are present
  template:
    src: "msmtprc.j2"
    dest: "/etc/msmtp/msmtprc{{ (item.name == 'default') | ternary('.000.', '.') }}{{ item.name }}"
    mode: "0640"
    owner: "{{ msmtp_owner }}"
    group: "{{ msmtp_group }}"
  with_items:
    - "{{ msmtp_accounts }}"

- name: Ensure account specific aliases conf files are present
  template:
    src: "aliases.j2"
    dest: "/etc/msmtp/aliases{{ (item.name == 'default') | ternary('.000.', '.') }}{{ item.name }}"
    mode: "0640"
    owner: "{{ msmtp_owner }}"
    group: "{{ msmtp_group }}"
  with_items:
    - "{{ msmtp_accounts }}"

- name: Assemble msmtp config file from fragmets
  assemble:
    src: /etc/msmtp
    dest: /etc/msmtprc
    mode: "0640"
    owner: "{{ msmtp_owner }}"
    group: "{{ msmtp_group }}"
    delimiter: ""
    regexp: "^msmtprc\\..+"
